yotpo:
  deploymentName: demo-config-map
  namespace: default
  chartName: yotpo/microservice-config
  chartPath: http://chartmuseum.k8s.yotpodev.com/
  chartVersion: 0.1.0

clusters:
  production:
    - name: demo-consul-config
      data:
        CONSUL_SERVICE_NAME: "demo"
        CONSUL_TAGS: "LB=Int, LBHost=demo.us-east-1.yotpo.xyz"
    - name: demo-config
      data:
        SECRET_FROM_VAULT: "vault:PATH/TO/SECRET#KEY_NAME"
        KEY1: "VALUE"
        KEY2: "VALUE"
  staging:
    - name: demo-config
      data:
        SECRET_FROM_VAULT: "vault:PATH/TO/SECRET#KEY_NAME"
        KEY1: "VALUE"
        KEY2: "VALUE"

